baseURL = "https://adrianduan.github.io/"
theme = "hugo-coder"
defaultContentLanguage = "en"
# defaultContentLanguageInSubdir = true
title = "Adrian's Blog"
canonifyurls = true
paginate = 20

# disqusShortname = "yourdiscussshortname"

[params]
author = "Adrian Duan"
avatarurl = "https://avatars0.githubusercontent.com/u/26034046?s=460&u=34d039009d0e8cc0fb02f0a6a1fbe40de1c1920c&v=4"
description = "Adrian Duan's personal website"
info = "Software Engineer"
keywords = "blog,developer,personal"
favicon_16 = "/img/favicon-16x16.png"
favicon_32 = "/img/favicon-32x32.png"
hideCopyright = false
hideCredits = true
colorScheme = "auto"
custom_css = []
custom_js = []
enableEmoji = true
enableTwemoji = false
math = true
rtl = false

# Social links
[[params.social]]
icon = "fab fa-github"
name = "Github"
url = "https://github.com/adrianduan/"
weight = 1

[[params.social]]
icon = "fas fa-envelope"
name = "Email"
url = "mailto:adrian.duanjing@gmail.com"
weight = 2

[[params.social]]
icon = "fab fa-telegram-plane"
name = "Telegram"
url = "https://t.me/adrian_duanjing"
weight = 3

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
weight = 4
url = "https://adrianduan.github.io/index.xml"
rel = "alternate"
type = "application/rss+xml"

[markup]
[markup.highlight]
lineNos = true
lineNumbersInTable = true
style = "monokai"

[languages]
[languages.en]
languagename = "ğŸ‡ºğŸ‡¸"
[languages.en.params]
footerContent = "All content on this website is licensed under a <a href='https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en'>CC BY-NC-SA 4.0</a> International License"
dateFormat = "Jan. 2, 2006"
[languages.en.menu]
[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"
[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"

[languages.zh-cn]
languagename = "ğŸ‡¨ğŸ‡³"
[languages.zh-cn.params]
footerContent = "æœ¬ç«™çš„æ‰€æœ‰å†…å®¹é‡‡ç”¨<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh'>CC BY-NC-SA 4.0</a>å›½é™…è®¸å¯åè®®è¿›è¡Œè®¸å¯"
dateFormat = "2006å¹´01æœˆ02æ—¥"
[languages.zh-cn.menu]
[[languages.zh-cn.menu.main]]
name = "æ–‡ç« "
weight = 1
url = "posts/"
[[languages.zh-cn.menu.main]]
name = "å…³äº"
weight = 2
url = "about/"
